sudo: required
dist: bionic
os: linux
language: node_js
node_js: 10.14.1
services:
  - docker

before_script:
  - npm install

jobs:
  include:
    - stage: unit test
      script:
        - npm run build:ts
        - npm run test:unit

